package com.jorder.bank.model.enums;

public enum Category {
    CRIANÇAS_E_JOVENS,
    ACOMPANHAMENTO_DE_ADULTOS,
    CASA_E_VIDA_DOMESTICA,
    ANIMAIS_E_PLANTAS,
    ATIVIDADES_MANUAIS,
    ATIVIDADES_ADMINISTRATIVAS,
    ENSINO_E_APRENDIZAGEM,
    BELEZA_E_CUIDADOS_PESSOAIS
}